### ISSUE TITLE
Collapsing sigmabot.py using a generic meta defined function

### ISSUE THREAD

**Issue by cafebedouin** [Eeysirhc/sigmabot#56]
I'm not quite sure how to do this in Python but this is the general idea:
```
@client.command()
async def bot_cmd(cmd_var):
        async def cmd_var(ctx)
        await ctx.send(fq.faq_cmd_var())
```
Most every command has this format. So, if we just allow a variable, we could do all the work with just one or two functions (if modifiers cannot be included in some kind of if statement). Maybe also include a pre-processing that checks the commands against an allowed-commands array, and does nothing or has a generic error: "cmd_var is not a valid sigmabot command. Try messaging @sigmabot for .help." if the command is not in the array.

**Comment by Eeysirhc** [comment]
Created a class instead (see https://github.com/Eeysirhc/sigmabot/commit/3ba8bc47dca1c1110a7b1c63233064b7d23eee0b) for the different categories and if we think it is a problem in the future we can resurface this to streamline code....seems straightforward and explicit for now since figuring out how to add modifiers or not increases complexity.
